module.exports = {
    SIGN_SUCCESS: "You have successfully signed up!",
    OTP_SEND :"Otp send successfully with Registered Mobile Number",
    RESEND_OTP :"Otp Resend successfully with Registered Mobile Number",
    EMAIL_VERIFYED: "Email successfully verified!",
    FIRST_LOGIN: "First-time login successfully made!",
    LOGIN_SUCCESS: "Your have successfully logged in!",
    REFER_RECEIVE: "Your have received a Referral code!",
    REFER_SEND: "Referral code sent successfully!",
    LOGIN_SUCCESS_VERIFYER: "Successfully logged in through Verifyer.me!",
    RESET_PASSWORD: "Please reset your password!",
    PASSWORD_CHANGE: "Hi user, Your password has been changed successfully.",
    KTC_REQUEST: "You have made a KYC request!",
    REVIEW_PENDING: "Please review your pending documents!",
    ACCEPT_DOCUMENT: "You have accepted the document request!",
    REQUEST_REJECT: "Document request has been rejected!",
    TEMPLATE_SAVED: "Template saved!",
    DOCUMENT_REQUEST: "You successfully made a document request to (username)",
    ACCESS_GIVEN: "Access given to (name)",
    ACCESS_REJECT: "Access Restricted!",
    REQUEST_MADE: "Request successfully made!",
    DOCUMENT_ACCEPT: "Documents accepted!",
    DOCUMENT_REJECT: "Documents rejected!",
    SUB_ACCOUNT_ADDED: "Sub account successfully added!",
    UPDATE_REWARD: "Reward updated successfully",
    DOCUMENT_UPLOAD: "Document upload successful!",
    DOCUMENT_SHARE: "Document shared successfully!",
    IPV_BOOK_REQUEST: "IPV booking request made!",
    BGV_BOOK_REQUEST: "BGV booking request made!",
    IPV_BOOK: "IPV booked successfully!",
    BGV_BOOK: "BGV booked successfully!",
    PROFILE_UPDATE: "Profile Updated successfully!",
    REFER_ORG: "Successfully referred to (Org name)",
    REFFER_USER: "Successfully referred to (user name)",
    ADDRESS_ADDED: "Address added successfully!",
    ADDRESS_REMOVED: "Address removed successfully!",
    PASSWORD_CHANGED: "Password changed successfully!",
    PASSWORD_UPDATED: "Password updated!",
    BANK_ADDED: "Your bank has been added!",
    BANK_UPDATE: "Bank updated successfully!",
    BANK_DELETED: "Bank Details Deleted successfully",
    PAYMENT_SUCCESS: "Payment successful!",
    DOCUMENT_REQUEST_SUCCESS: "Document request successfully sent.",
    DIGITAL_VERIFICATION_SUCCESS: "Request for digital verification successfully made!",
    BLOCK_SHARING : "Document share blocked share successfully",
    UNBLOCK_SHARING : "Document share unblocked successfully",


};
