require('dotenv').config();
const path = require('path');
const projectRoot = path.join(__dirname, '..');

module.exports = {
  ENVIRONMENT: process.env.ENVIRONMENT || '',
  PROJECT_NAME: process.env.PROJECT_NAME || '',
  PROJECT_ROOT: projectRoot,
  PORT: process.env.PORT || '',
  MONGODB_URL: process.env.MONGODB_URL || '',
  DEBUG_FILE: process.env.DEBUG_FILE || '',
  JWT_SECRET: process.env.JWT_SECRET || '',
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || '',
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || '',
  TWILIO_FROM: process.env.TWILIO_FROM || '',
  SMPP_USERID: process.env.SMPP_USERID || '',
  SMPP_PASSWORD: process.env.SMPP_PASSWORD || '',
  SMPP_SENDERID: process.env.SMPP_SENDERID || '',
  SMPP_PE_ID : process.env.SMPP_PE_ID || '',
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASSWORD: process.env.MAIL_PASSWORD,
  MAIL_SERVER: process.env.MAIL_SERVER,
  SMPP_COUNTRYCODE: process.env.SMPP_COUNTRYCODE || '',
  SMS: process.env.SMS || '',
  SMTP_SENDER: process.env.SMTP_SENDER || '',
  SMTP_PASSWORD: process.env.SMTP_PASSWORD || '',
  SMTP_HOST: process.env.SMTP_HOST || '',
  SMTP_PORT: process.env.SMTP_PORT || '',
  SMTP_SENDER_NAME: process.env.SMTP_SENDER_NAME || '',
  APP_URL: process.env.APP_URL || '',
  RABBIT_MQ_CONNECTION_URL: process.env.RABBIT_MQ_CONNECTION_URL || '',
  REDIS_HOST: process.env.REDIS_HOST || '',
  REDIS_PORT: process.env.REDIS_PORT || '',
  REDIS_DB: process.env.REDIS_DB || '',
  REDIS_PASSWORD: process.env.REDIS_PASSWORD || '',
  CREDIT_FACTOR_WITH_AMOUNT: process.env.CREDIT_FACTOR_WITH_AMOUNT || '',
  PROMO_FACTOR_WITH_CREDIT: process.env.PROMO_FACTOR_WITH_CREDIT || '',
  MEDILOCKS_WHATSAPP_BACKEND_API: process.env.MEDILOCKS_WHATSAPP_BACKEND_API || '',
  DOWNLOAD_FOLDER_PATH: process.env.DOWNLOAD_FOLDER_PATH || '',
  DOWNLOAD_FOLDER_BASE_URL: process.env.DOWNLOAD_FOLDER_BASE_URL || '',
  ONESIGNAL_APP_ID: process.env.ONESIGNAL_APP_ID || '',
  ONESIGNAL_API_KEY: process.env.ONESIGNAL_API_KEY || '',
  SHAREURL: process.env.SHAREURL || '',
  VOUCHER_BUYERGUID: process.env.VOUCHER_BUYERGUID || '',
  VOUCHER_PASSWORD: process.env.VOUCHER_PASSWORD || '',
  EMAIL_VERIFY_LINK: process.env.EMAIL_VERIFY_LINK || '',
  PAYMENT_API_KEY: process.env.PAYMENT_API_KEY || '',
  PAYMENT_API_PASSWORD: process.env.PAYMENT_API_PASS || '',
  CALLBACK_URI: process.env.CALLBACK_URI || '',
  FILE_PATH : process.env.FILE_PATH || '',

  FILE_PATH_REPORT : process.env.FILE_PATH_REPORT || '',
  FILE_PATH_PROFILE : process.env.FILE_PATH_PROFILE || '',
  DOC_URL_REPORT : process.env.DOC_URL_REPORT || '',
  DOC_URL_PROFILE : process.env.DOC_URL_PROFILE || '',

  DOC_URL : process.env.DOC_URL || '',
  URI : process.env.URI || '',
  X_CLIENT_SECRET : process.env.X_CLIENT_SECRET || '',
  X_CLIENT_ID : process.env.X_CLIENT_ID || '',
  LOGO : process.env.LOGO || '',
  SUPPORT_EMAIL : process.env.SUPPORT_EMAIL || '',
  REDIRECT_LINK : process.env.REDIRECT_LINK || '',
  PAYMENT_URI: process.env.PAYMENT_URI || '',
  PAYMENT_LINK_EXP_TIME: process.env.PAYMENT_LINK_EXP_TIME || '',
  REDIRECT_AFTER_SUCCESSFAIL_PAYMENT: process.env.REDIRECT_AFTER_SUCCESSFAIL_PAYMENT || '',
  APP_URL_FRONT: process.env.APP_URL_FRONT || '',
  WATER_MARK_IMG : process.env.WATER_MARK_LOGO || '',

  PROMOTE_SEND_SMS_URL : process.env.PROMOTE_SEND_SMS_URL || '',
  PROMOTE_SEND_SMS_KEY : process.env.PROMOTE_SEND_SMS_KEY || '',
  PROMOTE_SEND_SMS_COMPAIGN : process.env.PROMOTE_SEND_SMS_COMPAIGN || '',
  PROMOTE_SEND_SMS_TYPE : process.env.PROMOTE_SEND_SMS_TYPE || '',
  PROMOTE_SEND_SMS_PEID : process.env.PROMOTE_SEND_SMS_PEID || '',

  PROMOTE_SEND_SMS_ROUTE_PROMO : process.env.PROMOTE_SEND_SMS_ROUTE_PROMO || '',
  PROMOTE_SEND_SMS_SENDER_PROMO : process.env.PROMOTE_SEND_SMS_SENDER_PROMO || '',

  PROMOTE_SEND_SMS_SENDER_OTP : process.env.PROMOTE_SEND_SMS_SENDER_OTP || '',
  PROMOTE_SEND_SMS_ROUTE_OTP : process.env.PROMOTE_SEND_SMS_ROUTE_OTP || '',

  PROMOTE_SEND_SMS_SENDER_TRANS : process.env.PROMOTE_SEND_SMS_SENDER_TRANS || '',
  PROMOTE_SEND_SMS_ROUTE_TRANS : process.env.PROMOTE_SEND_SMS_ROUTE_TRANS || '',

  CUR_URL_PAN : process.env.CU_URL_PAN || '',
  CUR_URL_ADHAR : process.env.CU_URL_ADHAR || '',
  CUR_URL_DL : process.env.CU_URL_DL || '',
  PROMOTE_GET_HEADER_AND_TEMPLATE : process.env.PROMOTE_GET_HEADER_AND_TEMPLATE || '',
  PROMOTE_SEND_MISC_URL : process.env.PROMOTE_SEND_MISC_URL || '',

  THIRDPARTY_URL : process.env.THIRDPARTY_URL || '',
  THIRDPARTY_API_KEY : process.env.THIRDPARTY_API_KEY || '',
  THIRDPARTY_AGENCY_KEY : process.env.THIRDPARTY_AGENCY_KEY || '',
  CU_URL_DETECT : process.env.CU_URL_DETECT || '',

  PROMOTE_GET_HEADER : process.env.PROMOTE_GET_HEADER || '',
  PROMOTE_GET_TEMPLATE : process.env.PROMOTE_GET_TEMPLATE || '',
  Token : process.env.Token || '',
  TECHNO_THIRDPARTY_URL : process.env.Token || '',
  TECHNO_THIRDPARTY_API_KEY : process.env.Token || '',
  TECHNO_THIRDPARTY_PASSWORD : process.env.Token || '',

  TRANSACTION_SEND_SMS_URL : process.env.TRANSACTION_SEND_SMS_URL || '',
  TRANSACTION_UESR : process.env.TRANSACTION_UESR || '',
  TRANSACTION_PASSWORD : process.env.TRANSACTION_PASSWORD || '',
  TRANSACTION_SENDER :  process.env.TRANSACTION_SENDER || '',
  TRANSACTION_PEID : process.env.TRANSACTION_PEID || '',
  TRANSACTION_CONTENTID : process.env.TRANSACTION_CONTENTID || '',


  EMAIL_SENDER_NAME:process.env.EMAIL_SENDER_NAME || '',
  SENDER_EMAIL : process.env.SENDER_EMAIL || '',
  SENDER_API_KEY : process.env.SENDER_API_KEY || '',

};

